spring:
  application:
    name: api-gateway

  server:
    port: 8080

  cloud:
    gateway:
      routes:
        - id: user
          uri: lb://user
          predicates:
            - Path=/user/**
        - id: recruiter
          uri: lb://recruiter
          predicates:
            - Path=/recruiter/**

  data:
    redis:
      host: localhost
      port: 6379

eureka:
  client:
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    prefer-ip-address: true
